version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env.test
    environment:
      DATABASE_URL: postgresql+asyncpg://dev:dev123@postgres:5432/sgiv_db
    depends_on:
      - postgres
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: ./frontend/.env
    volumes:
      - ./frontend/src:/app/src

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sgiv_db}
      POSTGRES_USER: ${POSTGRES_USER:-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
